defaults:
  - _self_
  - server: localhost
  - ego: default
  - entity: default
  - traffic_manager: default
  - scenario: attach_only/default
  - splatsim: default
  - map: odaibatest

server:
  host: localhost
  port: 2000
  timeout_seconds: 3600.0

traffic_manager:
  port: 8100

map:
  name: ???
  xodr_path: null
  lanelet2_path: null

ego:
  vehicle_type: vehicle.mini.cooper
  initial_speed_kmh: 0.0
  spawn_lanelet_id: 100
  spawn_s: 5.0
  is_autoware: true

entity:
  ground_projection_ray_distance_upper: 5.0
  ground_projection_ray_distance_lower: 10.0
  spawn_retry_max_count: 10
  spawn_retry_t_step: 0.1
  spawn_retry_z_step: 0.5

simulation:
  fixed_delta_seconds: 0.05

splatsim:
  scene_yaml: ???
  image_topic: /splatsim/image_raw
  camera_info_topic: /splatsim/camera_info
  frame_id: splatsim_camera
